routes:
  /: home
  /about/:
    permalink: /about/
    template: authors

collections:
  /post/:
    permalink: /post/{slug}/
    template: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/